import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { resolve, extname, sep } from 'node:path';
import assert from 'node:assert/strict';
const { chromium } = await import('../.cache/qa/node_modules/playwright/index.mjs');
const root = resolve('dist');
const server = createServer(async (req, res) => {
  const pathname = new URL(req.url, 'http://localhost').pathname;
  const path = resolve(root, '.' + (pathname === '/' ? '/index.html' : pathname));
  if (!path.startsWith(root + sep)) { res.writeHead(403).end(); return; }
  try { res.setHeader('Content-Type', { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html', '.csv': 'text/csv' }[extname(path)] ?? 'application/octet-stream'); res.end(await readFile(path)); }
  catch { res.writeHead(404).end(); }
});
await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
let browser;
try {
  browser = await chromium.launch({ channel: process.env.QA_BROWSER ?? 'msedge', headless: true });
  const origin = `http://127.0.0.1:${server.address().port}`;
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(origin);
  await page.locator('#advancedCategory').click();
  await page.getByRole('group', { name: '発展・応用', exact: true }).getByRole('button', { name: /Boosting/ }).click();
  assert.equal(new URL(page.url()).hash, '#xgboost');
  await page.locator('#xgb-accuracy').filter({ hasNotText: '—' }).waitFor();
  assert.equal(await page.locator('#xgboostTask').getAttribute('aria-pressed'), 'true');
  assert.match(await page.locator('#xgb-split').textContent(), /学習800件・検証200件/);
  await page.locator('#xgb-next').click();
  await page.locator('#xgb-history-value').filter({ hasText: '1 / 1本' }).waitFor();
  const one = await page.locator('#xgb-valid-loss').textContent();
  await page.locator('#xgb-play').click();
  await page.locator('#xgb-history-value').filter({ hasText: /[2-9] \/ [2-9]本/ }).waitFor();
  await page.locator('#xgb-play').click();
  const paused = await page.locator('#xgb-history-value').textContent();
  await page.waitForTimeout(1000);
  assert.equal(await page.locator('#xgb-history-value').textContent(), paused);
  await page.locator('#xgb-finish').click();
  await page.locator('#xgb-status').filter({ hasText: '60本の学習が完了' }).waitFor({ timeout: 120000 });
  await page.locator('#xgb-history').fill('1');
  assert.equal(await page.locator('#xgb-valid-loss').textContent(), one);
  await page.locator('#xgb-sample').selectOption({ index: 2 });
  assert.match(await page.locator('#xgb-sample-label').textContent(), /CSV/);
  await page.locator('#xgb-dataset').selectOption('moons');
  await page.locator('#xgb-history-value').filter({ hasText: '0 / 0本' }).waitFor();
  await page.locator('#xgb-mode').selectOption('all');
  assert.match(await page.locator('#xgb-mode-note').textContent(), /2列/);
  await page.locator('#xgb-rate').fill('0.2');
  await page.locator('#xgb-finish').click();
  await page.locator('#xgb-reset').click();
  await page.waitForTimeout(200);
  assert.equal(await page.locator('#xgb-history-value').textContent(), '0 / 0本');
  await page.locator('#xgb-next').click();
  await page.locator('#xgb-history-value').filter({ hasText: '1 / 1本' }).waitFor();
  await page.locator('#basicCategory').click();
  await page.locator('#clsTask').click();
  assert.equal(await page.locator('#xgboost').isVisible(), false);
  await page.goBack();
  await page.locator('#xgboost').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#xgb-dataset').inputValue(), 'moons');
  assert.equal(await page.locator('#xgb-history-value').textContent(), '1 / 1本');
  await page.goForward();
  assert.equal(await page.locator('#supervisedWorkspace').isVisible(), true);
  await page.goto(`${origin}/#xgboost`);
  await page.locator('#xgb-accuracy').filter({ hasNotText: '—' }).waitFor();
  await page.locator('#xgb-dataset').selectOption('circles');
  await page.locator('#xgb-mode').selectOption('all');
  await page.locator('#xgb-finish').click();
  await page.locator('#xgb-status').filter({ hasText: '60本の学習が完了' }).waitFor({ timeout: 120000 });
  await page.reload();
  await page.locator('#xgb-accuracy').filter({ hasNotText: '—' }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await mkdir('.cache/qa/screenshots', { recursive: true });
  await page.screenshot({ path: '.cache/qa/screenshots/xgboost-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: '.cache/qa/screenshots/xgboost-desktop.png', fullPage: true });
  const missing = await browser.newPage();
  await missing.route('**/boosting/data/classification.csv', (route) => route.fulfill({ status: 404, body: '' }));
  await missing.goto(`${origin}/#xgboost`);
  await missing.locator('#xgb-status').filter({ hasText: 'データエラー:' }).waitFor();
  assert.match(await missing.locator('#xgb-status').textContent(), /classification\.csv.*HTTP 404/);
  await missing.close();
  assert.deepEqual(errors, []);
  console.log('XGBoost browser navigation, training, history, controls and responsive checks passed');
} finally { await browser?.close(); server.close(); }
